### ISSUE TITLE
No permissions to create backup directory

### ISSUE THREAD

**Issue by o1y** [MWDelaney/trellis-backup#1]
The task **Create backup directory** fails:

`"msg": "There was an issue creating /srv/www/example.com/backup as requested: [Errno 13] Permission denied: '/srv/www/example.com/backup'", "path": "/srv/www/example.com/backup", "state": "absent"`

Solution is adding `become: yes` to server.yml as follows:

```
- name: Set up backups
  hosts: web:&{{ env }}
  become: yes
  roles:
    - { role: backup, tags: [backup] }
    - { role: Stouts.backup, tags: [backup] }
```
