### ISSUE TITLE
mysql_root_user is undefined

### ISSUE THREAD

**Issue by o1y** [MWDelaney/trellis-backup#2]
I don't know why `mysql_root_user` is not available in that scope, but as defined in the mariadb task from trellis the root user is always `root` so I've hardcoded that username to the `create backup jobs` task:

```
- name: Create backup jobs
  set_fact:
   [...]

    backup_mysql_user: root
    backup_mysql_pass: "{{ mysql_root_password }}"
```
